[build]
publish = "public"
command = "gulp && hugo -t cnab"

[context.production.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "gulp &&  hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "gulp && hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.3"

[context.branch-deploy]
command = "gulp &&  hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.40.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
